volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/seitleio
      o: bind

services:
  grav:
    build: ./
    ports:
      - 127.0.0.1:7452:80
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=seitle.io,www.seitle.io
      - LETSENCRYPT_HOST=seitle.io,www.seitle.io
    volumes:
      - grav-data:/var/www/html