version: "3"

services:
  site:
    build: ./
    ports: 
      - 127.0.0.1:6453:80
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=seitle.io,www.seitle.io,blackfeet-it.de,www.blackfeet-it.de,wo7ke.de,www.wo7ke.de
      - LETSENCRYPT_HOST=seitle.io,www.seitle.io,blackfeet-it.de,www.blackfeet-it.de,wo7ke.de,www.wo7ke.de